services:
  - type: web
    name: vcet-alumni-frontend
    env: node
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://alumniconnect-1.onrender.com
    healthCheckPath: /
    autoDeploy: true 